import asyncio
import logging
import re
import time
from enum import Enum
from dataclasses import dataclass
from typing import Dict, Any
import json
import os

_LINK_RE = re.compile(r"^Link:\s*(\S+)", re.M)
_TITLE_RE = re.compile(r"^Title:\s*(.+)$", re.M)
# Core MCP SDK client imports
from mcp import Client
from mcp.client.session import ClientSession
from mcp.client.sse import sse_client

from src.system_design.graph.state import ResearchState

logger = logging.getLogger(__name__)

# --- Configuration Constants ---
MCP_SERVER_SSE_URL = os.getenv("MCP_SERVER_SSE_URL", "http://mcp-server-service:8080/sse")
_BRAVE_NO_RESULTS_MARKER = "no results found"


# =====================================================================
# 🛠️ FIXED COMPONENT 1: FETCH STATUS ENUM & DATACLASS
# =====================================================================
class FetchStatus(Enum):
    OK = "ok"            # genuine, usable result content
    EMPTY = "empty"       # source responded fine, no results exist
    BLOCKED = "blocked"   # source is refusing/soft-blocking us
    ERROR = "error"       # transport/parse/unexpected failure

@dataclass
class FetchResult:
    status: FetchStatus
    data: str = ""
    source: str = ""


# =====================================================================
# 🛠️ FIXED COMPONENT 2: THE EXCEPTION UNWRAPPER LOGIC
# =====================================================================
def _flatten_exception(exc: BaseException) -> str:
    """
    Unwraps nested ExceptionGroups generated by anyio/MCP internals
    to surface the actual underlying root cause error message.
    """
    if hasattr(exc, "exceptions"):  # ExceptionGroup (py3.11+)
        return "; ".join(_flatten_exception(sub) for sub in exc.exceptions)
    return f"{type(exc).__name__}: {exc}"


# --- Circuit Breaker States & Config ---
class BreakerState(Enum):
    CLOSED = "closed"        # Tool flows freely
    OPEN = "open"            # All traffic blocked instantly
    HALF_OPEN = "half_open"  # Single test call allowed

class CircuitBreaker:
    def __init__(self):
        self.state = BreakerState.CLOSED
        self.failure_count = 0
        self.failure_threshold = 3
        
        # Cooldown timing settings (in seconds)
        self.base_cooldown = 10.0
        self.current_cooldown = 10.0
        self.next_valid_time = 0.0
        
        # Synchronization lock for state transitions across concurrent tasks
        self.lock = asyncio.Lock()

    async def check_state(self):
        """Evaluates and shifts state dynamically based on timestamps."""
        async with self.lock:
            if self.state == BreakerState.OPEN and time.time() >= self.next_valid_time:
                logger.warning("[Breaker] Cooldown expired. Moving to HALF-OPEN state.")
                self.state = BreakerState.HALF_OPEN
            return self.state

    async def record_success(self):
        """Resets metrics when a test call or normal call succeeds."""
        async with self.lock:
            if self.state == BreakerState.HALF_OPEN:
                logger.info("[Breaker] Test call succeeded! Closing breaker and restoring full traffic.")
                self.current_cooldown = self.base_cooldown  # Reset backoff
            self.state = BreakerState.CLOSED
            self.failure_count = 0

    async def record_failure(self):
        """Increments failures and triggers exponential backoff if threshold is met."""
        async with self.lock:
            self.failure_count += 1
            if self.state == BreakerState.HALF_OPEN or self.failure_count >= self.failure_threshold:
                self.state = BreakerState.OPEN
                self.next_valid_time = time.time() + self.current_cooldown
                logger.critical(
                    f"[Breaker] Failure recorded. Breaker enters OPEN state. "
                    f"Blocking traffic for {self.current_cooldown:.1f} seconds."
                )
                self.current_cooldown *= 2.0

# Initialize a single global instance of the breaker for this node execution lifetime


def _extract_sources(parsed: dict, raw_text: str) -> list[dict]:
    sources = []
    seen = set()
    for item in parsed.get("sources") or []:
        if isinstance(item, dict):
            url = (item.get("url") or "").strip()
            title = (item.get("title") or "").strip()
        else:
            url, title = str(item).strip(), ""
        if url and url not in seen:
            seen.add(url)
            sources.append({"title": title, "url": url})
    titles = _TITLE_RE.findall(raw_text or "")
    links = _LINK_RE.findall(raw_text or "")
    for i, url in enumerate(links):
        if url not in seen:
            seen.add(url)
            title = titles[i].strip() if i < len(titles) else ""
            sources.append({"title": title, "url": url})
    return sources


async def execute_safe_fallback(question: str, reason: str = "circuit_breaker") -> dict:
    return {
        "sub_question": question,
        "status": "failed",
        "source": "unavailable",
        "reason": reason,
        "sources": [],
        "data": ""
    }

# --- Core Async LangGraph Node ---
async def batch_research_node(state: ResearchState) -> dict:
    sub_questions = state.sub_questions if hasattr(state, "sub_questions") else state.get("sub_questions", [])
    if not sub_questions:
        return {"researched_results": []}

    breaker = CircuitBreaker()

    logger.info(f"[Batch Researcher] Streamlining {len(sub_questions)} queries through a highly resilient breaker.")
    
    # Strictly limit system concurrency to 2 active network execution operations
    semaphore = asyncio.Semaphore(int(os.getenv("RESEARCH_CONCURRENCY", "4")))

    status_map = {
        FetchStatus.OK: "success",
        FetchStatus.EMPTY: "no_data",
        FetchStatus.BLOCKED: "blocked",
        FetchStatus.ERROR: "failed",
    }

    try:
        # 🚨 THE COMPATIBILITY LAYER FIX:
        # Establish the SSE transport stream and use ClientSession context wrapper explicitly.
        # This completely bypasses Client vs ClientSession signature collisions across different SDK release builds.
        async with sse_client(url=MCP_SERVER_SSE_URL) as (read_stream, write_stream):
            async with ClientSession(read_stream, write_stream) as session:
                
                # Execute protocol version negotiation and capability handshakes once
                await session.initialize()
                logger.info("[SSE Client] High-concurrency MCP pipeline connection established.")
                # ClientSession request/response IDs are stateful; serialize only the
                # protocol call while keeping parsing and result handling concurrent.
                tool_call_lock = asyncio.Lock()

                # Step 2: Define a sequential-safe worker function
                async def safe_worker_pipeline(sub_question: str) -> dict:
                    # Enforce the concurrent worker execution limit
                    async with semaphore:
                        
                        
                        # 2. Check the real-time status of the breaker right before making the call
                        current_breaker_state = await breaker.check_state()
                        if current_breaker_state == BreakerState.OPEN:
                            logger.info(f"[Resilient Pool] Breaker is OPEN. Auto-routing to cache for: '{sub_question}'")
                            return await execute_safe_fallback(sub_question)

                                               # 3. Proceed to call the tool over the active connection
                        logger.info(f"[Resilient Pool] Funneling query via Breaker [{current_breaker_state.value}]: '{sub_question}'")
                        try:
                            # Calls your FastMCP tool container setup
                            async with tool_call_lock:
                                mcp_response = await session.call_tool(
                                    name="brave_web_search",
                                    arguments={"query": sub_question},
                                )
                            
                            # 🚨 THE FASTMCP PARSING FIX:
                            # FastMCP returns a specialized response object. We safely convert the result content 
                            # directly to a string frame or pull its content blocks natively.
                            raw_payload = ""
                            if hasattr(mcp_response, "content") and mcp_response.content:
                                raw_payload = "\n".join(
                                    block.text for block in mcp_response.content if hasattr(block, "text")
                                ).strip()
                            elif isinstance(mcp_response, str):
                                raw_payload = mcp_response.strip()
                            elif hasattr(mcp_response, "text"):
                                raw_payload = mcp_response.text.strip()

                            try:
                                parsed = json.loads(raw_payload)
                            except (json.JSONDecodeError, TypeError):
                                raise ValueError(f"Non-JSON or malformed tool response: {raw_payload[:200]}")

                            if parsed.get("status") == "error":
                                raise ValueError(f"Tool reported error: {parsed.get('data')}")
                            if parsed.get("status") == "quota_exceeded":
                                logger.warning(f"[Resilient Pool] Tavily quota hit for: '{sub_question}' — using fallback.")
                                return await execute_safe_fallback(sub_question)
                            if parsed.get("status") == "empty":
                                # legitimate empty result — not a breaker-worthy failure
                                await breaker.record_success()
                                return {
                                    "sub_question": sub_question,
                                    "status": "no_data",
                                    "source": "tavily",
                                    "sources": [],
                                    "data": ""
                                }

                            extracted_findings = parsed.get("data", "")
                            sources = _extract_sources(parsed, extracted_findings)
                            await breaker.record_success()
                            return {
                                "sub_question": sub_question,
                                "status": "success",
                                "source": "tavily",
                                "sources": sources,
                                "data": extracted_findings
                            }

                        except Exception as tool_error:
                            clean_error = _flatten_exception(tool_error)
                            logger.error(f"[Resilient Pool] Individual query execution failed: {clean_error}")
                            
                            # Trip breaker metrics and route this specific task to fallback
                            await breaker.record_failure()
                            return await execute_safe_fallback(sub_question)

                # Step 3: Run the structured worker tasks concurrently
                tasks = [safe_worker_pipeline(q) for q in sub_questions]
                completed_results = await asyncio.gather(*tasks)

    except Exception as global_session_error:
        # Step 4: Handle any global session crashes or server drops gracefully
        session_root_cause = _flatten_exception(global_session_error)
        logger.critical(f"[Batch Researcher] Master SSE transport link failure: {session_root_cause}")
        
        # Trip breaker metrics globally
        await breaker.record_failure()
        
        # Instantly run the fallback queue loop for all remaining items to ensure the graph never stalls
        fallback_tasks = [execute_safe_fallback(q, reason="session_crash") for q in sub_questions]
        completed_results = await asyncio.gather(*fallback_tasks)

    return {"researched_results": completed_results}
